# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Understanding Machine Code
email: trueprogandy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to machine language and its execution, using a simple
  microcomputer simulation written in Java.
baseurl: "/cpu" # the subpath of your site, e.g. /blog
url: "https://trueprog.github.io" # the base hostname & protocol for your site
github_username:  trueprog

# Build settings
markdown: kramdown
include: ['_pages']

sass:
  style: :compressed

collections:
- lessons

collections:
  lessons:
    output: true

defaults:
  - scope:
      path: ""
      type: lessons
    values:
      layout: page